- name: Play Variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: Play Variables from files
  hosts: localhost
  ## vars_files works only on play level
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from file
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: Task level variables
  hosts: localhost
  tasks:
    - name: print play variable
      vars:  ## These vars are only for this task, next task on same play cannot access it.
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{URL}}

##### Inventory level variables #######

- name: Inventory level variables
  hosts: all
  tasks:
    - name: print play variable from inventory
      ansible.builtin.debug:
        msg: "URL = {{URL}}, Hostname of Server = {{ansible_hostname}}"

###### To Register a variable #######
- name: Register a variable
  hosts: localhost
  tasks:
    - name: get uptime output
      ansible.builtin.shell: uptime
      register: out
    - name: printout
      ansible.builtin.debug:
        msg: "{{out}}"
